# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_lawyers_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyers',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
