# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
    ]
