# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160426_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
    ]
