# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160424_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emailid',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
