# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20160424_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emailid',
            new_name='email',
        ),
    ]
