# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160426_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequests',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
