# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingrequests_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequests',
            name='from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
