# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_bookingrequests_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequests',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
